import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog"

import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"

import { Toaster } from "@/components/ui/toaster"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-black ${inter.className}`}>
        <nav className="sticky top-0 z-10 bg-black backdrop-filter backdrop-blur-lg bg-opacity-30 border-b border-gray-200">
          <div className="max-w-5xl mx-auto px-4">
            <div className="flex items-center justify-between h-16">
              <span className="text-2xl text-white font-semibold">Logo</span>
              <div className="flex space-x-4 text-white">
                <Sheet >
                  <SheetTrigger>Profile</SheetTrigger>
                  <SheetContent className="dark">
                    <SheetHeader>
                      <SheetTitle>Profile</SheetTitle>
                      <SheetDescription>
                        This action cannot be undone. This will permanently delete your account
                        and remove your data from our servers.
                      </SheetDescription>
                    </SheetHeader>
                  </SheetContent>
                </Sheet>

                <AlertDialog>
                  <AlertDialogTrigger className="text-red-500 dark">Logout</AlertDialogTrigger>
                  <AlertDialogContent className="dark">
                    <AlertDialogHeader className="text-white">
                      <AlertDialogTitle>Are you sure you want to log out?</AlertDialogTitle>
                    </AlertDialogHeader>
                    <AlertDialogFooter >
                      <AlertDialogCancel className="text-white">Cancel</AlertDialogCancel>
                      <AlertDialogAction>Continue</AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              </div>
            </div>
          </div>
        </nav>
        <div className="p-10">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
